
service: trigger-dynamo

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: TODO_TABLE
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStreams
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: working
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
          - AttributeName: working
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        
functions:
  todoInsert:
    handler: handler.todoInsert
    events:
      - http:
          path: todo
          method: post
          cors: true
  todoUpdate:
    handler: handler.todoUpdate
    events:
      - http:
          path: todo
          method: put
          cors: true